training:
  totalTimesteps: 1000000

env:
  numSimulationSteps: 10
  normalizeObs: True
  # Action normalization scale
  torqueScale:
    [
      99,
      159,
      159,
      299,
      159,
      99,
      99,
      159,
      159,
      299,
      159,
      99,
      # 144,
      # 144,
      # 144,
      # 144,
      # 90,
      # 90,
      # 144,
      # 144,
      # 90,
      # 90,
    ]
  # Stop conditions
  maxTime: 1000
  minHeight: 0.8 # if 0 no check is performed on the height of the robot
  # Reward parameters
  weightPosture: 1
  weightCommand: 0.5
  weightAlive: 2

designer:
  left_foot_name: "left_sole_link"
  right_foot_name: "right_sole_link"
  urdf_path: "/opt/openrobots/share/example-robot-data/robots/talos_data/robots/talos_reduced.urdf"
  srdf_path: "/opt/openrobots/share/example-robot-data/robots/talos_data/srdf/talos.srdf"
  robot_description: ""
  controlled_joints_names:
    [
      root_joint,
      leg_left_1_joint,
      leg_left_2_joint,
      leg_left_3_joint,
      leg_left_4_joint,
      leg_left_5_joint,
      leg_left_6_joint,
      leg_right_1_joint,
      leg_right_2_joint,
      leg_right_3_joint,
      leg_right_4_joint,
      leg_right_5_joint,
      leg_right_6_joint,
      # torso_1_joint,
      # torso_2_joint,
      # arm_left_1_joint,
      # arm_left_2_joint,
      # arm_left_3_joint,
      # arm_left_4_joint,
      # arm_right_1_joint,
      # arm_right_2_joint,
      # arm_right_3_joint,
      # arm_right_4_joint,
    ]
  toolFramePos: [0, -0.02, -0.0825]
