training:
  totalTimesteps: 100000

env:
  numSimulationSteps: 10
  normalizeObs: True
  # Action normalization scale
  torqueScale:
    [
      # 99,
      # 159,
      # 159,
      # 299,
      # 159,
      # 99,
      # 99,
      # 159,
      # 159,
      # 299,
      # 159,
      # 99,
      # 144,
      # 144,
      144,
      144,
      90,
      90,
      # 144,
      # 144,
      # 90,
      # 90,
    ]
  # Stop conditions
  maxTime: 1000
  minHeight: 0.8 # if 0 no check is performed on the height of the robot
  # Target
  targetPosition: [0.6,0.4,1.1]
  # Reward parameters
  weightTarget: 1
  weightCommand: 5

designer:
  URDF: "/talos_data/robots/talos_reduced.urdf"
  SRDF: "/talos_data/srdf/talos.srdf"
  controlledJoints:
    [
      # root_joint,
      # leg_left_1_joint,
      # leg_left_2_joint,
      # leg_left_3_joint,
      # leg_left_4_joint,
      # leg_left_5_joint,
      # leg_left_6_joint,
      # leg_right_1_joint,
      # leg_right_2_joint,
      # leg_right_3_joint,
      # leg_right_4_joint,
      # leg_right_5_joint,
      # leg_right_6_joint,
      # torso_1_joint,
      # torso_2_joint,
      arm_left_1_joint,
      arm_left_2_joint,
      arm_left_3_joint,
      arm_left_4_joint,
      # arm_left_5_joint,
      # arm_left_6_joint,
      # arm_left_7_joint,
      # arm_right_1_joint,
      # arm_right_2_joint,
      # arm_right_3_joint,
      # arm_right_4_joint,
    ]
  toolPosition: [0, -0.02, -0.0825]
