designer:
  URDF: "/talos_data/robots/talos_reduced.urdf"
  SRDF: "/talos_data/srdf/talos.srdf"
  controlledJoints:
    [
      # root_joint,
      # leg_left_1_joint,
      # leg_left_2_joint,
      # leg_left_3_joint,
      # leg_left_4_joint,
      # leg_left_5_joint,
      # leg_left_6_joint,
      # leg_right_1_joint,
      # leg_right_2_joint,
      # leg_right_3_joint,
      # leg_right_4_joint,
      # leg_right_5_joint,
      # leg_right_6_joint,
      # torso_1_joint,
      # torso_2_joint,
      arm_left_1_joint,
      arm_left_2_joint,
      arm_left_3_joint,
      arm_left_4_joint,
      # arm_left_5_joint,
      # arm_left_6_joint,
      # arm_left_7_joint,
      # arm_right_1_joint,
      # arm_right_2_joint,
      # arm_right_3_joint,
      # arm_right_4_joint,
    ]
  toolPosition: [0, -0.02, -0.0825]

env:
  numSimulationSteps: 1
  timeStepSimulation: 1e-3
  normalizeObs: True
  # Stop conditions
  maxTime: 10 # Maximum epoch time in seconds
  minHeight: 0.8 # if 0 no check is performed on the height of the robot
  # Target
  targetPosition: [0.6,0.4,1.1]
  # Reward parameters
  w_target_pos: 1
  w_control_reg: 1
  w_penalization_truncation: 10

SAC:

training:
  numEnv: 6
  totalTimesteps: 100000