training:
  totalTimesteps: 1000000

env:
  numSimulationSteps: 10
  normalizeObs: True
  # Action normalization scale
  torqueScale:
    [
      99,
      159,
      159,
      299,
      159,
      99,
      99,
      159,
      159,
      299,
      159,
      99,
      144,
      144,
      144,
      144,
      90,
      90,
      144,
      144,
      90,
      90,
    ]
  # Stop conditions
  maxTime: 1000
  minHeight: 0.6 # if 0 no check is performed on the height of the robot
  # Reward parameters
  weightPosture: 1
  weightCommand: 0.5
  weightAlive: 4

designer:
  leftFootName: "left_sole_link"
  rightFootName: "right_sole_link"
  urdfPath: "/opt/openrobots/share/example-robot-data/robots/talos_data/robots/talos_reduced.urdf"
  srdfPath: "/opt/openrobots/share/example-robot-data/robots/talos_data/srdf/talos.srdf"
  robotDescription: ""
  controlledJointsNames:
    [
      root_joint,
      leg_left_1_joint,
      leg_left_2_joint,
      leg_left_3_joint,
      leg_left_4_joint,
      leg_left_5_joint,
      leg_left_6_joint,
      leg_right_1_joint,
      leg_right_2_joint,
      leg_right_3_joint,
      leg_right_4_joint,
      leg_right_5_joint,
      leg_right_6_joint,
      torso_1_joint,
      torso_2_joint,
      arm_left_1_joint,
      arm_left_2_joint,
      arm_left_3_joint,
      arm_left_4_joint,
      arm_right_1_joint,
      arm_right_2_joint,
      arm_right_3_joint,
      arm_right_4_joint,
    ]
  toolFramePos: [0, -0.02, -0.0825]
