training:
  name: "red_torque_08"
  environment_quantity: 1 # Number of environments used to collect data
  total_timesteps: 1000000 # Total number of training timesteps
  learning_rate: 0.0003 # Learning rate of the algorithm
  log_interval: 10 # Number of timesteps between logging events
  learning_starts: 100 # Number of timesteps before starting to learn
  train_freq: 2 # Update the model every train_freq steps. Set to None to disable the interval update
  gamma: 0.95 # Discount factor
  batch_size: 128 # Minibatch size for each gradient update
  n_sampled_goal: 1 # Number of sampled goals to optimize the distance to
  buffer_size: 1e6 # Size of the replay buffer
  tau: 0.010 # Target network update rate
  verbose: 2 # 0: no output 1: info 2: debug

environment:
  numSimulationSteps: 10
  timeStepSimulation: 1e-3
  normalizeObs: False
  randomInit: True # Choose to randomize the position of controlled joint arount the initial position 
  # (a quarter around the limits and the initial position currently)
  limitPosScale: 1
  limitVelScale: 1
  torqueScaleCoeff: 0.8

  # Stop conditions
  maxTime: 30 # Maximum epoch time in seconds
  minHeight: 0.9 # if 0 no check is performed on the height of thed robot
  lowerLimitPos: [-0.25, -0.05, 0.9]
  upperLimitPos: [0.05, 0.05, 1.1]
  # Target
  # targetType can be "fixed" or "reachable" or "box" or "sphere" around the shoulder
  targetType: "sphere"
  targetPosition: [0.1482729,  0.46236133, 0.68072397]
  # targetPosition: [0.14, 0.46, 0.6834647]
  targetSizeLow: [-0.1, -0.1, -0.1]
  targetSizeHigh: [0.1, 0.1, 0.1]
  targetRadius: 0.3
  shoulderPosition: [0.3482729,  0.46236133, 1.08072397]
  
  # Reward parameters
  w_target_pos: 10
  w_control_reg: 0.05
  w_penalization_truncation: 5

robot_designer:
  # URDF: "/talos_data/robots/talos_full_v2.urdf"
  URDF: "/talos_data/robots/talos_reduced.urdf"
  SRDF: "/talos_data/srdf/talos.srdf"
  controlledJoints:
    [
      # root_joint,
      # leg_left_1_joint,
      # leg_left_2_joint,
      # leg_left_3_joint,
      # leg_left_4_joint,
      # leg_left_5_joint,
      # leg_left_6_joint,
      # leg_right_1_joint,
      # leg_right_2_joint,
      # leg_right_3_joint,
      # leg_right_4_joint,
      # leg_right_5_joint,
      # leg_right_6_joint,
      torso_1_joint,
      torso_2_joint,
      arm_left_1_joint,
      arm_left_2_joint,
      arm_left_3_joint,
      arm_left_4_joint,
      arm_left_5_joint,
      arm_left_6_joint,
      arm_left_7_joint,
      # arm_right_1_joint,
      # arm_right_2_joint,
      # arm_right_3_joint,
      # arm_right_4_joint,
    ]

  # Initial position of the robot
  toolPosition: [0.0, 0.0, 0.0]
  # toolPosition: [0, -0.02, -0.0825]