training:
  name: "local_training"
  total_timesteps: 10000000 # Total number of training timesteps
  log_interval: 100 # Number of timesteps between logging events

SAC:
  model_param:
    {
      policy: "MultiInputPolicy",
      verbose: 2,
      learning_starts: 1000,
      tensorboard_log: "logs/",
      device: "cpu",
      buffer_size: 1000000,
      learning_rate: 0.0003,
      train_freq: 2,
      gamma: 0.95,
      batch_size: 128,
      tau: 0.01,
      ent_coef: "auto_0.04",
      policy_kwargs: {
        net_arch: [512, 512, 512],
      },
    }
  HerReplayBuffer_param:
    replay_buffer_kwargs:
      {
        copy_info_dict: True,
        n_sampled_goal: 1,
        goal_selection_strategy: "future",
      }


environment:
  nb_environments: 1 # Number of environments used to collect data
  numSimulationSteps: 10
  timeStepSimulation: 1e-3
  normalizeObs: False
  randomInit: True # Choose to randomize the position of controlled joint arount the initial position 
  # (a quarter around the limits and the initial position currently)
  limitPosScale: 1
  limitVelScale: 1
  torqueScaleCoeff: 1
  thresholdSuccess: 0.05

  # Stop conditions
  maxTime: 30 # Maximum epoch time in seconds
  lowerLimitPos: [-0.25, -0.05, 0.9]
  upperLimitPos: [0.1, 0.05, 1.3]
  # Target
  # targetType can be "fixed" or "reachable" or "box" or "sphere" around the shoulder
  targetType: "sphere"
  targetPosition: [0.25, 0.43, 1.1]
  targetSizeLow: [-0.1, -0.1, -0.1]
  targetSizeHigh: [0.1, 0.1, 0.1]
  targetRadius: 0.3
  
  rewardType: "dense" # "sparse", "dense" or "mix" if want to mix both
  thresholdSuccess: 0.05 # Distance threshold to consider that the target is reached
  # Reward parameters
  w_target_reached: 10
  w_target_pos: 10
  w_control_reg: 0.1
  w_penalization_truncation: 4


robot_designer:
  # URDF: "/talos_data/robots/talos_full_v2.urdf"
  URDF: "/talos_data/robots/talos_reduced.urdf"
  SRDF: "/talos_data/srdf/talos.srdf"
  controlledJoints:
    [
      # root_joint,
      # leg_left_1_joint,
      # leg_left_2_joint,
      # leg_left_3_joint,
      # leg_left_4_joint,
      # leg_left_5_joint,
      # leg_left_6_joint,
      # leg_right_1_joint,
      # leg_right_2_joint,
      # leg_right_3_joint,
      # leg_right_4_joint,
      # leg_right_5_joint,
      # leg_right_6_joint,
      torso_1_joint,
      torso_2_joint,
      arm_left_1_joint,
      arm_left_2_joint,
      arm_left_3_joint,
      arm_left_4_joint,
      arm_left_5_joint,
      arm_left_6_joint,
      arm_left_7_joint,
      # arm_right_1_joint,
      # arm_right_2_joint,
      # arm_right_3_joint,
      # arm_right_4_joint,
    ]

  # Initial position of the robot
  # toolPosition: [0.0, 0.0, 0.0]
  toolPosition: [0, -0.02, -0.0825]