training:
  name: "torque_rew"
  total_timesteps: 10000 # Total number of training timesteps
  log_interval: 10 # Number of episodes between logging events
  check_freq: 1000 # Number of timesteps between saving checkpoints

SAC:
  model_param:
    { policy: "MlpPolicy", tensorboard_log: "logs/", device: "cpu", verbose: 2 }

environment:
  nb_environments: 1 # Number of environments used to collect data
  timeStepSimulation: 1e-3
  numOCPSteps: 10
  normalizeObs: True
  # Stop conditions
  maxTime: 4 # Maximum epoch time in seconds
  minHeight: 0.8 # if 0 no check is performed on the height of the robot
  # Target
  targetType: "fixed"
  targetPosition: [0.6, 0.4, 1.1]
  # Reward parameters
  distanceThreshold: 0.005
  w_success: 10
  w_distance: 2
  w_penalization_truncation: 100
  w_penalization_torque: 0.001

robot:
  designer:
    urdf_path: "/opt/openrobots/share/example-robot-data/robots/talos_data/robots/talos_reduced.urdf"
    srdf_path: "/opt/openrobots/share/example-robot-data/robots/talos_data/srdf/talos.srdf"
    controlled_joints_names:
      [
        root_joint,
        leg_left_1_joint,
        leg_left_2_joint,
        leg_left_3_joint,
        leg_left_4_joint,
        leg_left_5_joint,
        leg_left_6_joint,
        leg_right_1_joint,
        leg_right_2_joint,
        leg_right_3_joint,
        leg_right_4_joint,
        leg_right_5_joint,
        leg_right_6_joint,
        torso_1_joint,
        torso_2_joint,
        arm_left_1_joint,
        arm_left_2_joint,
        arm_left_3_joint,
        arm_left_4_joint,
        arm_left_5_joint,
        arm_left_6_joint,
        arm_left_7_joint,
        arm_right_1_joint,
        arm_right_2_joint,
        arm_right_3_joint,
        arm_right_4_joint,
      ]
    robot_description: ""
    left_foot_name: "left_sole_link"
    right_foot_name: "right_sole_link"
    toolPosition: [0, -0.02, -0.0825]

  OCP:
    horizon_length: 30
    time_step: 0.02
    w_state_reg: 0.02
    w_control_reg: 0.001
    w_limit: 1000
    w_com_pos: 500
    w_gripper_pos: 5
    w_gripper_rot: 30
    w_gripper_vel: 2
    limit_scale: 1
    state_weights:
      [
        500,
        500,
        500,
        1000,
        1000,
        1000,
        500,
        500,
        500,
        500,
        1000,
        1000,
        500,
        500,
        500,
        500,
        1000,
        1000,
        100,
        200,
        100,
        100,
        100,
        100,
        1,
        1,
        1,
        500,
        500,
        500,
        500,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        10,
        10,
        10,
        10,
        10,
        10,
        10,
        10,
        10,
        10,
        10,
        10,
        10,
      ]
    control_weights:
      [
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
      ]
