training:
  name: "3joints_unlimited"
  total_timesteps: 150000 # Total number of training timesteps
  log_interval: 500 # Number of episodes between logging events
  check_freq: 5000 # Number of timesteps between saving checkpoints
  number_eval: 100

SAC:
  model_param:
    policy: "MlpPolicy"
    tensorboard_log: "logs/"
    device: "cpu"
    verbose: 0

environment:
  nb_environments: 1 # Number of environments used to collect data
  timeStepSimulation: 1e-3
  numOCPSteps: 5
  actionType: "full_range" # full_range / differential
  actionScale: 1
  clipAction: False
  normalizeObs: False
  historyObs: 0
  predictionSize: 3
  controlled_joints_names: [
      # torso_1_joint,
      # torso_2_joint,
      arm_left_1_joint,
      arm_left_2_joint,
      # arm_left_3_joint,
      arm_left_4_joint,
    ]
  # Stop conditions
  maxTime: 4 # Maximum epoch time in seconds
  minHeight: 0.8 # if 0 no check is performed on the height of the robot
  # Target
  targetType: "box"
  targetPosition: [0.7, 0.3, 1]
  targetSizeLow: [-0.2, -0.3, -0.3]
  targetSizeHigh: [0.2, 0.3, 0.3]
  # Reward parameters
  distanceThreshold: 0.005
  w_success: 10
  w_distance: 5
  w_penalization_truncation: 500
  w_penalization_torque: 0.001
  # Parameter to activate extra Pal's limits
  extra_limits: False

robot:
  designer:
    urdf_type: "private_pal_limited" # custom, example_robot_data, private_pal, public_pal
    controlled_joints_names: [
        root_joint,
        leg_left_1_joint,
        leg_left_2_joint,
        leg_left_3_joint,
        leg_left_4_joint,
        leg_left_5_joint,
        leg_left_6_joint,
        leg_right_1_joint,
        leg_right_2_joint,
        leg_right_3_joint,
        leg_right_4_joint,
        leg_right_5_joint,
        leg_right_6_joint,
        torso_1_joint,
        torso_2_joint,
        arm_left_1_joint,
        arm_left_2_joint,
        arm_left_3_joint,
        arm_left_4_joint,
        # arm_left_5_joint,
        # arm_left_6_joint,
        # arm_left_7_joint,
        arm_right_1_joint,
        arm_right_2_joint,
        arm_right_3_joint,
        arm_right_4_joint,
      ]
    robot_description: ""
    left_foot_name: "left_sole_link"
    right_foot_name: "right_sole_link"
    end_effector_position: [0, -0.02, -0.0825]

  OCP:
    delay: 1
    horizon_length: 30
    time_step: 0.02
    w_state_reg: 0.02
    w_control_reg: 0.001
    w_state_limits: 1000
    w_control_limit: 500
    w_com_pos: 500
    w_gripper_pos: 5
    w_gripper_rot: 1
    w_gripper_vel: 2
    limit_scale: 0.95
    limit_speed: true
    base:
      position: [500, 500, 500]
      orientation: [1000, 1000, 1000]
      linear_velocity: [1, 1, 1]
      angular_velocity: [1, 1, 1]
    joints:
      leg_left_1_joint: [500, 1, 1]
      leg_left_2_joint: [500, 1, 1]
      leg_left_3_joint: [500, 1, 1]
      leg_left_4_joint: [500, 1, 1]
      leg_left_5_joint: [1000, 1, 1]
      leg_left_6_joint: [1000, 1, 1]
      leg_right_1_joint: [500, 1, 1]
      leg_right_2_joint: [500, 1, 1]
      leg_right_3_joint: [500, 1, 1]
      leg_right_4_joint: [500, 1, 1]
      leg_right_5_joint: [1000, 1, 1]
      leg_right_6_joint: [1000, 1, 1]
      torso_1_joint: [100, 10, 1]
      torso_2_joint: [200, 10, 1]
      arm_left_1_joint: [100, 10, 1]
      arm_left_2_joint: [100, 10, 1]
      arm_left_3_joint: [100, 10, 1]
      arm_left_4_joint: [100, 10, 1]
      arm_left_5_joint: [1, 10, 1]
      arm_left_6_joint: [1, 10, 1]
      arm_left_7_joint: [1, 10, 1]
      arm_right_1_joint: [500, 10, 1]
      arm_right_2_joint: [500, 10, 1]
      arm_right_3_joint: [500, 10, 1]
      arm_right_4_joint: [500, 10, 1]
