name: talos-rl
dependencies:
  - python>=3.8,<4.0
  - conda-forge::compilers
  - conda-forge::pkg-config
  - conda-forge::yaml-cpp
  - conda-forge::crocoddyl>=2.1.0
  - conda-forge::example-robot-data>=4.0.7,<5.0.0
  - conda-forge::pybullet>=3.2.5,<4.0.0
  - conda-forge::pyyaml>=6.0,<7.0
  - conda-forge::tensorboard>=2.13.0,<3.0.0
  - pytorch::pytorch>=2.0.1,<3.0.0
  - pip
  - pip:
    - stable-baselines3>=2.0.0a10,<3.0.0
